language: python
before_script:
  - python /home/travis/build/SunPower/SolarUtils/setup.py bdist_wheel
  - pip install /home/travis/build/SunPower/SolarUtils/dist/SolarUtils-*.whl
# command to run tests
script: py.test
